### PR TITLE
Add extension banner to the hompage

### LINKED ISSUE #164: Add extension banner to the hompage
[Issuehunt badges](https://issuehunt.io/r/PREreview/rapid-prereview/issues/164)

I think it would be useful to point out that a user does not have the extension installed. I saw this on [PubPeer](https://pubpeer.com/), and quite like that idea. 

I suggest adding a message such as "You have not yet installed the Outbreak Science Rapid PREreivew browser extension to enable requesting, adding and/or reading rapid reviews on other websites. Install it [here](https://outbreaksci.prereview.org/extension)!"

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [prereview prereview](https://issuehunt.io/u/prereview) ($100.00)

### Submitted pull Requests
- [#168 Add extension banner to the hompage](https://issuehunt.io/r/PREreview/rapid-prereview/pull/168)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by ChaituVR**
Fixes #164 

Note: 

- Banner is displayed only on Home Page
- On click of close button - banner will be hided even after reload (stored in localstorage)
- No change in extension code
- Hided by default on mobile screen
- Desktop Screenshot
  image

- Medium size screens -> FeedBack banner is moved a little up
  image

- On Mobile banner is hidden and FeedBack banner moved back to previous position
  image

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#164: Add extension banner to the hompage](https://issuehunt.io/repos/208844948/issues/164)
---
</details>

### CODE REVIEW

**Comment by harumhelmy** [comment]
Thanks for this thorough and clean work @ChaituVR. There's currently a discussion going on about the UX of the site with having so many calls to action (the top banner, the feedback ask, and this extension banner), so I'll have to wait on approving/merging this for now.

**Comment by dasaderi** [comment]
@ChaituVR Thank you so much. I assume the system will detect if the user has the extension and not show the banner, correct? 

@harumhelmy Let's discuss your point on the many calls to action at our next meeting. I think you have a point. Maybe time to take the Give Feedback out.

**Comment by ChaituVR** [comment]
@dasaderi  Ya it will not show up when user have the extension and also when user clicks close button in this banner

**Comment by dasaderi** [comment]
@ChaituVR Super! Thank you! 

@harumhelmy, could you please review the code and merge the PR? We just briefly discussed the clutter issue in our call with @jheretic. I'll start a new issue thread about that, but we all agree this banner for the integration is useful.

**Comment by ChaituVR** [comment]
@harumhelmy now added underline for the link
image

**Pull request merged**
