### PR TITLE
Isolate extension shell from dock-right UX changes

### PR DESCRIPTION
**Pull request by sajacy**
*Do not merge*

This is simply a demonstration branch (on top of the `shellux` branch) that isolates the extension, so it is unaffected by the changes for wide-screen mode.

If this tests out ok, i can move this onto #87 so it can be merged all together.

@sballesteros @halmos @georgiamoon @dwins

### CODE REVIEW

**Comment by sajacy** [comment]
Tested locally, LGTM.  The question order rendering has the desired updates, while the extension retains the drawer/overlay layout.

image

**Comment by sballesteros** [comment]
I wonder if we could not avoid the large CSS duplication introduced by `extension-shell.css` here.
For instance we could pass a custom class to the shell (e.g. `<Shell className='shell--app'>`) from `<ExtensionFallback>`.

**Comment by sajacy** [comment]
I think that kind of change will be more effective in combination with a later update to a user-controlled layout.  Using the class doesn't negate need to split for `@media(...)` (which answers the "when to dock" question) versus the `shell-app` class answering the (hopefully) shorter-lived meta-question of "if this is the extension, allow CSS to dock".  Having user-controlled layout makes the meta-question obsolete, but will probably need similar class-based CSS structure.

**Comment by sballesteros** [comment]
Sorry not sure I follow. 
The new `src/components/extension-shell.css` is almost a full copy of  `/src/components/shell.css` which makes it hard to maintain. Why not just overwriting the part that need to be changed in `shell.css` based on `.shell.shell--app` (which will only be defined when we are _not_ in the extension).
Apologies if I am missing smtg here.

Otherwise I thought we realized that a user-controlled layout was probably not a good idea given that a shell docked on the right is only helpful when there is no overlap (per @halmos https://github.com/PREreview/rapid-prereview/pull/87#issuecomment-610953972)

**Comment by sajacy** [comment]
My reasoning goes like this:

The `extension-shell.css` is an exact copy of what was in `shell.css`, which seems in line with separating the extension from site/app.  The modifications to `shell.css` are `@media`-specific changes only, so the shell's DOM structure/classing doesn't need to change, and none of the shell code needed to change except for checking when to set `maximized` (only because the style attribute is directly written on dragging).   The alternative, a marker class `.shell--app`, will require the same changes, substituting the `.shell.shell--app` for the `@media` blocks, but also the detection of the viewport width within the JS.  In this case, it's more "coupled" to include the `.shell.shell--app` styling + the viewport detection JS in the extension src.

Re: user-controlled layout, I was thinking a button that toggled between bottom-overlay and right-docked layouts, not a right-anchored overlay.

**Comment by sballesteros** [comment]
Ok thanks. So far we tried hard to maximize style, user experience and code re-use in between the extension and the site version. IMHO duplicating a fair amount of CSS creates future maintenance / style consistency issues and I don't see why it's necessary here (I don't get why that would require JS logic). 
That being said I currently lack time to provide an example that could better illustrate my point so I feel free to ignore me as I don't want to be an annoying blocker here.

**Comment by sajacy** [comment]
No worries - thanks for the attention to code architecture - I agree it's important!  I'd be happy to take more input (maybe you can open an Issue?).  Closing this, since it has served its purpose.

**Pull request closed without merging**
